### PR TITLE
Close Issue #2 Add a new method convert2RMQMessage

### PR DESCRIPTION
**Pull request by a2888409**
https://github.com/rocketmq/rocketmq-jms/issues/2

### CODE REVIEW

**Comment by dongeforever** [comment]
Close Issue #2 而不是Close Issue #{2}

**Comment by dongeforever** [comment]
加一个单元测试吧，RocketMQ Message 转成JMS Message 再转回来，看看是否还与最初的一致

**Comment by dongeforever** [comment]
@a2888409  please pay attention to the reviews above

**Comment by a2888409** [comment]
ok, I will improve it as soon as possible

**Comment by dongeforever** [comment]
@a2888409 happy new year.  please have a look at the new reviews. 

 for (String name : properties.stringPropertyNames()) {
+            if (MessageConst.systemKeySet.contains(name)) {
+                if (systemKeys == null) {


if the systemKeySet has contained it, we should use specific method to set the value, such setTags setTimeDelayLevel and so on. please take a look at the implementation of RMQ message.


RMQ message has two kind of properties: one is user-defined, we can set these using putUserProperty; one is system-defined, we cannot just put it but using specific method such as setTags, setTimeDelayLevel, setWaitStoreMsgOK and so on.

**Comment by a2888409** [comment]
thanks for your explanation, i will improve it later.

**Comment by Zhang-Ke** [comment]
@a2888409 What's your name is the QQ group "RocketMQ-JMS"?

**Comment by a2888409** [comment]
my qq is 122274659, and the nick name in group is called rain

**Pull request merged**
